name: Deploy to Cloudflare Pages (staging)

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Build
        run: npm run build
      - run: npm i -g wrangler
      - name: Publish to Cloudflare Pages (staging)
        run: |
          wrangler pages deploy out \
            --project-name "${{ secrets.CF_PROJECT_NAME }}" \
            --branch "${{ secrets.STAGING_BRANCH }}" \
            --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
